import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
# [colors.primary]
# background = "#303446"
# foreground = "#C6D0F5"
# dim_foreground = "#C6D0F5"
# bright_foreground = "#C6D0F5"
#
# [colors.cursor]
# text = "#303446"
# cursor = "#F2D5CF"
#
# [colors.vi_mode_cursor]
# text = "#303446"
# cursor = "#BABBF1"
#
# [colors.search.matches]
# foreground = "#303446"
# background = "#A5ADCE"
#
# [colors.search.focused_match]
# foreground = "#303446"
# background = "#A6D189"
#
# [colors.footer_bar]
# foreground = "#303446"
# background = "#A5ADCE"
#
# [colors.hints.start]
# foreground = "#303446"
# background = "#E5C890"
#
# [colors.hints.end]
# foreground = "#303446"
# background = "#A5ADCE"
#
# [colors.selection]
# text = "#303446"
# background = "#F2D5CF"
#
# [colors.normal]
# black = "#51576D"
# red = "#E78284"
# green = "#A6D189"
# yellow = "#E5C890"
# blue = "#8CAAEE"
# magenta = "#F4B8E4"
# cyan = "#81C8BE"
# white = "#B5BFE2"
#
# [colors.bright]
# black = "#626880"
# red = "#E78284"
# green = "#A6D189"
# yellow = "#E5C890"
# blue = "#8CAAEE"
# magenta = "#F4B8E4"
# cyan = "#81C8BE"
# white = "#A5ADCE"
#
# [colors.dim]
# black = "#51576D"
# red = "#E78284"
# green = "#A6D189"
# yellow = "#E5C890"
# blue = "#8CAAEE"
# magenta = "#F4B8E4"
# cyan = "#81C8BE"
# white = "#B5BFE2"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#EF9F76"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#F2D5CF"
#
[window]

opacity = 1

padding.x = 7
padding.y = 7

decorations = "None"
decorations_theme_variant = "Dark" # "Dark"

# Font settings
[font]
# family = "JetBrains Mono"
size = 7

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"
EDITOR = "nvim"

